language: node_js
node_js:
- '10'
cache:
  yarn: true
install:
- yarn install
script:
- yarn build
# deploy:
#   local_dir: dist/
#   provider: pages
#   skip_cleanup: true
#   github_token: "$GITHUB_TOKEN"
#   keep_history: false
#   name: simon
#   email: dengshuaihui@gmail.com
#   on:
#     branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_2248539243e5_key -iv $encrypted_2248539243e5_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
after_success:
- ssh simon_manager@47.107.127.139 touch trivas.text
addons:
  ssh_known_hosts: 47.107.127.139